name: event_reminder_app
description: Event Reminder App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # network
  dio_nexus: ^0.1.0
  dio: ^5.3.2
  connectivity_plus: ^4.0.2

  # storage
  shared_preferences: ^2.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3


  # ui kits
  bot_toast: ^4.0.4
  fluentui_system_icons: ^1.1.210
  animate_do: ^3.0.2
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.5
  lottie: ^2.6.0
  gap: ^3.0.1

  # state management
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0
  mobx: ^2.2.0
  provider: ^6.0.5
  flutter_riverpod: ^2.3.7

  # firebase
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  firebase_ui_auth: ^1.6.4
  firebase_ui_oauth_google: ^1.2.8
  firebase_ui_oauth_apple: ^1.2.8

  # core
  auto_route: ^7.8.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  permission_handler: ^10.4.3
  keyboard_dismisser: ^3.0.0
  get_it: ^7.6.0
  equatable: ^2.0.5


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/lottie/
  

  #fonts:
  #  - family: Montserrat
  #    fonts:
  #      - asset: fonts/Montserrat-Light.ttf
  #        weight: 300
  #      - asset: fonts/Montserrat-Regular.ttf
  #        weight: 400
  #      - asset: fonts/Montserrat-Medium.ttf
  #        weight: 500
  #      - asset: fonts/Montserrat-Bold.ttf
  #        weight: 700
  #      - asset: fonts/Montserrat-Black.ttf
  #        weight: 900
  #        style: italic
